# Generated by Django 5.1.2 on 2025-02-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onepiece", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="Default.png", null=True, upload_to="media/"
            ),
        ),
    ]
